Fix "path" property of CodeArchive: Was returning a tuple of strings instead of a single string representing the absolute path of the code archive. This resulted in "AttributeError: 'tuple' object has no attribute 'seek'" when trying to instantiate a Zipfile object in UserRequest._parse_archive